### ISSUE TITLE
Fails to run under fiji

### ISSUE THREAD

**Issue by jimmib78** [ClearVolume/ClearVolume#43]
(Fiji Is Just) ImageJ 2.0.0-rc-44/1.50e; Java 1.8.0_60 [64-bit]; Windows 8.1 6.3; 3693MB of 97973MB (3%)
 
java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: net/imglib2/util/Fraction
	at net.imagej.legacy.LegacyService.runLegacyCompatibleCommand(LegacyService.java:274)
	at net.imagej.legacy.DefaultLegacyHooks.interceptRunPlugIn(DefaultLegacyHooks.java:161)
	at ij.IJ.runPlugIn(IJ.java)
	at ij.Executer.runCommand(Executer.java:136)
	at ij.Executer.run(Executer.java:65)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: net/imglib2/util/Fraction
	at java.util.concurrent.FutureTask.report(Unknown Source)
	at java.util.concurrent.FutureTask.get(Unknown Source)
	at net.imagej.legacy.LegacyService.runLegacyCompatibleCommand(LegacyService.java:270)
	... 5 more
Caused by: java.lang.NoClassDefFoundError: net/imglib2/util/Fraction
	at de.mpicbg.jug.clearvolume.ClearVolumeUnsignedShortType.getEntitiesPerPixel(ClearVolumeUnsignedShortType.java:54)
	at de.mpicbg.jug.clearvolume.ClearVolumeUnsignedShortType.createSuitableNativeImg(ClearVolumeUnsignedShortType.java:320)
	at net.imglib2.img.array.ArrayImgFactory.create(ArrayImgFactory.java:62)
	at de.mpicbg.jug.clearvolume.ImgLib2ClearVolume.makeClearVolumeUnsignedShortTypeCopy(ImgLib2ClearVolume.java:380)
	at de.mpicbg.jug.clearvolume.ImgLib2ClearVolume.makeClearVolumeUnsignedShortTypeCopies(ImgLib2ClearVolume.java:354)
	at de.mpicbg.jug.clearvolume.ImgLib2ClearVolume.initRealImgs(ImgLib2ClearVolume.java:446)
	at de.mpicbg.jug.clearvolume.gui.ClearVolumeManager.run(ClearVolumeManager.java:182)
	at de.mpicbg.jug.clearvolume.gui.GenericClearVolumeGui.launchClearVolumeManager(GenericClearVolumeGui.java:303)
	at de.mpicbg.jug.clearvolume.gui.GenericClearVolumeGui.<init>(GenericClearVolumeGui.java:160)
	at de.mpicbg.jug.plugins.ClearVolumePlugin.run(ClearVolumePlugin.java:86)
	at org.scijava.command.CommandModule.run(CommandModule.java:201)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:167)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:126)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:65)
	at org.scijava.thread.DefaultThreadService$2.call(DefaultThreadService.java:191)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	... 1 more
Caused by: java.lang.ClassNotFoundException: net.imglib2.util.Fraction
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 19 more

**Comment by skalarproduktraum** [comment]
Hi James,

thanks for the report! I assume your Fiji installation is up-to-date and everything else works? 
The error itself looks a bit weird to me, as the imglib2.util.Fraction class is included with Fiji.

**Comment by jimmib78** [comment]
Hi Ulrik,
This was a fresh Fiji install and was updated.
The only other thing I am having issues with is the 3D viewer.

Not sure if it relates to ongoing development.  A lot of  things seem a
little unstable at the moment.
Could it be related to Java8?

**Comment by ctrueden** [comment]
I recommend using the __Help &#9654; Report a Bug__ plugin to generate the information about your installation, including which files are modified, missing, out of date, etc. You don't have to complete the bug report—just copy and paste the generated output regarding your JAR files here.

**Comment by skalarproduktraum** [comment]
As this was related to issues not related with ClearVolume, I'm closing the issue.
