### ISSUE TITLE
Throws errors and does not show image (Mac)

### ISSUE THREAD

**Issue by tischi** [ClearVolume/ClearVolume#52]
Hello, 

trying to run it, i get the following errors:

ClearGLWindow: GLProfile[GL3/GL3.hw]
1.0
1.0
1.0
Device name: 	 ClearCLDevice [mClearCLPlatform=ClearCLPlatform [name=Apple], name=Intel(R) Core(TM) i5-2557M CPU @ 1.70GHz] 
Exception in thread "SciJava-c3c9c95-Thread-0-FPSAWTAnimator#00-Timer0" com.jogamp.opengl.util.AnimatorBase$UncaughtAnimatorException: com.jogamp.opengl.GLException: Caught OpenCLException: OpenCL error: -10 -> CL_IMAGE_FORMAT_NOT_SUPPORTED on thread SciJava-c3c9c95-Thread-0-FPSAWTAnimator#00-Timer0
	at com.jogamp.opengl.util.AWTAnimatorImpl.display(AWTAnimatorImpl.java:92)
	at com.jogamp.opengl.util.AnimatorBase.display(AnimatorBase.java:452)
	at com.jogamp.opengl.util.FPSAnimator$MainTask.run(FPSAnimator.java:178)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)
Caused by: com.jogamp.opengl.GLException: Caught OpenCLException: OpenCL error: -10 -> CL_IMAGE_FORMAT_NOT_SUPPORTED on thread SciJava-c3c9c95-Thread-0-FPSAWTAnimator#00-Timer0
	at com.jogamp.opengl.GLException.newGLException(GLException.java:76)
	at jogamp.opengl.GLDrawableHelper.invokeGLImpl(GLDrawableHelper.java:1327)
	at jogamp.opengl.GLDrawableHelper.invokeGL(GLDrawableHelper.java:1147)
	at com.jogamp.newt.opengl.GLWindow.display(GLWindow.java:759)
	at com.jogamp.opengl.util.AWTAnimatorImpl.display(AWTAnimatorImpl.java:81)
	... 4 more

**Comment by tischi** [comment]
Some info about my system:

  Model Name:	MacBook Air
  Model Identifier:	MacBookAir4,2
  Processor Name:	Intel Core i5
  Processor Speed:	1.7 GHz
  Number of Processors:	1
  Total Number of Cores:	2
  L2 Cache (per Core):	256 KB
  L3 Cache:	3 MB
  Memory:	4 GB
  Boot ROM Version:	MBA41.0077.B14
  SMC Version (system):	1.73f66
  Serial Number (system):	C02H2083DJWQ
  Hardware UUID:	651A389B-6B2E-5791-9D77-7E97D11159C2

Intel HD Graphics 3000:

  Chipset Model:	Intel HD Graphics 3000
  Type:	GPU
  Bus:	Built-In
  VRAM (Dynamic, Max):	384 MB
  Vendor:	Intel (0x8086)
  Device ID:	0x0116
  Revision ID:	0x0009

**Comment by skalarproduktraum** [comment]
Hi @tischi,

unfortunately, the graphics chip your machine has (Intel HD Graphics 3000) is much too old to be supported by ClearVolume. It would also not really make sense to support it at all, as it only has 384 MB of memory available, with more than half of that usually already occupied by OSX. I'd suggest you try running ClearVolume on another machine. Anyway, we are going to add a more clear error message when an unsupported graphics chip is used in the next version.

Therefore, I'm closing the issue. Please let me know if you have further questions.

Sorry again!

**Comment by tischi** [comment]
Thank you for the speedy answer!
Makes sense!
Cheers, Christian
