### ISSUE TITLE
Can't open ClearMap plugin from ImageJ

### ISSUE THREAD

**Issue by djarecka** [ClearVolume/ClearVolume#60]
Hi,

I wanted to try using ClearMap and installed Java-8, ImageJ and installed ClearVolume plugin (ImageJ 2.0.0-rc-43/1.51o; Java 1.8.0_131 [64-bit]; Mac OS X 10.12.1). 
When I try  "Open in ClearVolume" I got an error in "Console":

```
[ERROR] Module threw error
java.lang.NoClassDefFoundError: com/jogamp/newt/awt/NewtCanvasAWT
	at de.mpicbg.jug.plugins.ClearVolumeClientPlugin.run(ClearVolumeClientPlugin.java:37)
	at org.scijava.command.CommandModule.run(CommandModule.java:201)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:167)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:126)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:65)
	at org.scijava.thread.DefaultThreadService$2.call(DefaultThreadService.java:191)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: com.jogamp.newt.awt.NewtCanvasAWT
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 10 more
```

I have also window with "Exception":

```
ImageJ 2.0.0-rc-43/1.51o; Java 1.8.0_131 [64-bit]; Mac OS X 10.12.1; 81MB of 9209MB (<1%)
 
java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: com/jogamp/newt/awt/NewtCanvasAWT
	at net.imagej.legacy.LegacyService.runLegacyCompatibleCommand(LegacyService.java:274)
	at net.imagej.legacy.DefaultLegacyHooks.interceptRunPlugIn(DefaultLegacyHooks.java:161)
	at ij.IJ.runPlugIn(IJ.java)
	at ij.Executer.runCommand(Executer.java:137)
	at ij.Executer.run(Executer.java:66)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: com/jogamp/newt/awt/NewtCanvasAWT
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at net.imagej.legacy.LegacyService.runLegacyCompatibleCommand(LegacyService.java:270)
	... 5 more
Caused by: java.lang.NoClassDefFoundError: com/jogamp/newt/awt/NewtCanvasAWT
	at de.mpicbg.jug.plugins.ClearVolumePlugin.run(ClearVolumePlugin.java:81)
	at org.scijava.command.CommandModule.run(CommandModule.java:201)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:167)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:126)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:65)
	at org.scijava.thread.DefaultThreadService$2.call(DefaultThreadService.java:191)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	... 1 more
Caused by: java.lang.ClassNotFoundException: com.jogamp.newt.awt.NewtCanvasAWT
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 10 more
```

Any suggestions what should I install more?

**Comment by imagejan** [comment]
@djarecka 

> and installed ClearVolume plugin...

How did you install ClearVolume? Did you follow the [instructions on the wiki](https://imagej.net/ClearVolume#Installing_ClearVolume_in_Fiji_or_ImageJ2)? If not, you're probably missing a _lot_ of dependencies...

**Comment by djarecka** [comment]
@imagejan : thanks for your answer! I guess I didn't get the point 4 from the wiki, since I have a new ImageJ and Java-8 I thought it's enough to choose ClearView. I've just installed Java-8 through ImageJ updates and ClearView started working.

Unfortunately I can't open a `tif` file that contains 2 channels, does it mean that you're not supporting it? or I should install something more (I use `Bio-Formats` plugin to open the file in ImageJ)

**Comment by skalarproduktraum** [comment]
Hey @djarecka,

would you be able to share that TIFF so we can have a look? If not, could you let us know what's the size, resolution, and data type (float, int, etc.)? 

Thanks!

**Comment by djarecka** [comment]
@skalarproduktraum : the original file was very big, but created  a smaller example that seems to have exactly the same problem: https://www.dropbox.com/s/ast94v7dcdrd8fg/cells_check_imagej.tif?dl=0

Please let me know if you have problem with downloading the file.

**Comment by skalarproduktraum** [comment]
@djarecka: Thanks for the image! It looks like BioFormats is picking up it's dimensions wrongly, and imports Z slices as timepoints. You can fix this on-the-fly by going to _Image > Hyperstacks > Reorder Hyperstack..._ and setting _Slices -> Frames_ and _Frames -> Slices_. It then opens fine in ClearVolume:

![screen shot 2017-06-15 at 09 45 18](https://user-images.githubusercontent.com/586495/27170817-9e7f2316-51af-11e7-969d-df5425e08476.png)

Please let me know whether this worked for you. 

cheers!

ulrik

**Comment by djarecka** [comment]
@skalarproduktraum : thanks! It works, i.e. I moved to the `CL_OUT_OF_RESOURCES` error now ;-)

**Comment by skalarproduktraum** [comment]
Okay, I'll close this issue for now then.
