### ISSUE TITLE
Error message preventing the 3D viewer to work

### ISSUE THREAD

**Issue by hadim** [ClearVolume/ClearVolume#67]
I am using a Fiji updated installation with the ClearVolume update site checked.

I am running Ubuntu 18.10 with kernel 4.13.0-16-generic on an Asus notebook laptop with the following graphic card: `Intel(R) HD Graphics Haswell Ultrabook GT3 reserved`

Here is the output of `clinfo`:

```
$ clinfo
X server found. dri2 connection failed! 
Number of platforms                               1
  Platform Name                                   Intel Gen OCL Driver
  Platform Vendor                                 Intel
  Platform Version                                OpenCL 2.0 beignet 1.3
  Platform Profile                                FULL_PROFILE
  Platform Extensions                             cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_byte_addressable_store cl_khr_3d_image_writes cl_khr_image2d_from_buffer cl_khr_depth_images cl_khr_spir cl_khr_icd cl_intel_accelerator cl_intel_subgroups cl_intel_subgroups_short cl_khr_gl_sharing
  Platform Extensions function suffix             Intel
X server found. dri2 connection failed! 
X server found. dri2 connection failed! 
X server found. dri2 connection failed! 
X server found. dri2 connection failed! 
X server found. dri2 connection failed! 

  Platform Name                                   Intel Gen OCL Driver
Number of devices                                 1
X server found. dri2 connection failed! 
X server found. dri2 connection failed! 
  Device Name                                     Intel(R) HD Graphics Haswell Ultrabook GT3 reserved
  Device Vendor                                   Intel
  Device Vendor ID                                0x8086
  Device Version                                  OpenCL 1.2 beignet 1.3
  Driver Version                                  1.3
  Device OpenCL C Version                         OpenCL C 1.2 beignet 1.3
  Device Type                                     GPU
  Device Profile                                  FULL_PROFILE
  Max compute units                               40
  Max clock frequency                             1000MHz
  Device Partition                                (core)
    Max number of sub-devices                     1
    Supported partition types                     None, None, None
  Max work item dimensions                        3
  Max work item sizes                             512x512x512
  Max work group size                             512
X server found. dri2 connection failed! 
X server found. dri2 connection failed! 
X server found. dri2 connection failed! 
  Preferred work group size multiple              16
  Preferred / native vector sizes                 
    char                                                16 / 8       
    short                                                8 / 8       
    int                                                  4 / 4       
    long                                                 2 / 2       
    half                                                 0 / 8        (n/a)
    float                                                4 / 4       
    double                                               0 / 2        (n/a)
  Half-precision Floating-point support           (n/a)
  Single-precision Floating-point support         (core)
    Denormals                                     No
    Infinity and NANs                             Yes
    Round to nearest                              Yes
    Round to zero                                 No
    Round to infinity                             No
    IEEE754-2008 fused multiply-add               No
    Support is emulated in software               No
    Correctly-rounded divide and sqrt operations  No
  Double-precision Floating-point support         (n/a)
  Address bits                                    32, Little-Endian
  Global memory size                              2147483648 (2GiB)
  Error Correction support                        No
  Max memory allocation                           1610612736 (1.5GiB)
  Unified memory for Host and Device              Yes
  Minimum alignment for any data type             128 bytes
  Alignment of base address                       1024 bits (128 bytes)
  Global Memory cache type                        Read/Write
  Global Memory cache size                        8192
  Global Memory cache line                        64 bytes
  Image support                                   Yes
    Max number of samplers per kernel             16
    Max size for 1D images from buffer            65536 pixels
    Max 1D or 2D image array size                 2048 images
    Base address alignment for 2D image buffers   4096 bytes
    Pitch alignment for 2D image buffers          1 bytes
    Max 2D image size                             8192x8192 pixels
    Max 3D image size                             8192x8192x2048 pixels
    Max number of read image args                 128
    Max number of write image args                8
  Local memory type                               Local
  Local memory size                               65536 (64KiB)
  Max constant buffer size                        134217728 (128MiB)
  Max number of constant args                     8
  Max size of kernel argument                     1024
  Queue properties                                
    Out-of-order execution                        No
    Profiling                                     Yes
  Prefer user sync for interop                    Yes
  Profiling timer resolution                      80ns
  Execution capabilities                          
    Run OpenCL kernels                            Yes
    Run native kernels                            Yes
    SPIR versions                                 1.2
  printf() buffer size                            1048576 (1024KiB)
  Built-in kernels                                __cl_copy_region_align4;__cl_copy_region_align16;__cl_cpy_region_unalign_same_offset;__cl_copy_region_unalign_dst_offset;__cl_copy_region_unalign_src_offset;__cl_copy_buffer_rect;__cl_copy_image_1d_to_1d;__cl_copy_image_2d_to_2d;__cl_copy_image_3d_to_2d;__cl_copy_image_2d_to_3d;__cl_copy_image_3d_to_3d;__cl_copy_image_2d_to_buffer;__cl_copy_image_3d_to_buffer;__cl_copy_buffer_to_image_2d;__cl_copy_buffer_to_image_3d;__cl_fill_region_unalign;__cl_fill_region_align2;__cl_fill_region_align4;__cl_fill_region_align8_2;__cl_fill_region_align8_4;__cl_fill_region_align8_8;__cl_fill_region_align8_16;__cl_fill_region_align128;__cl_fill_image_1d;__cl_fill_image_1d_array;__cl_fill_image_2d;__cl_fill_image_2d_array;__cl_fill_image_3d;
  Device Available                                Yes
  Compiler Available                              Yes
  Linker Available                                Yes
  Device Extensions                               cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_byte_addressable_store cl_khr_3d_image_writes cl_khr_image2d_from_buffer cl_khr_depth_images cl_khr_spir cl_khr_icd cl_intel_accelerator cl_intel_subgroups cl_intel_subgroups_short cl_khr_gl_sharing

NULL platform behavior
  clGetPlatformInfo(NULL, CL_PLATFORM_NAME, ...)  Intel Gen OCL Driver
X server found. dri2 connection failed! 
X server found. dri2 connection failed! 
X server found. dri2 connection failed! 
X server found. dri2 connection failed! 
  clGetDeviceIDs(NULL, CL_DEVICE_TYPE_ALL, ...)   Success [Intel]
X server found. dri2 connection failed! 
X server found. dri2 connection failed! 
X server found. dri2 connection failed! 
  clCreateContext(NULL, ...) [default]            Success [Intel]
X server found. dri2 connection failed! 
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_CPU)  No devices found in platform
X server found. dri2 connection failed! 
X server found. dri2 connection failed! 
X server found. dri2 connection failed! 
X server found. dri2 connection failed! 
X server found. dri2 connection failed! 
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_GPU)  Success (1)
    Platform Name                                 Intel Gen OCL Driver
    Device Name                                   Intel(R) HD Graphics Haswell Ultrabook GT3 reserved
X server found. dri2 connection failed! 
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_ACCELERATOR)  No devices found in platform
X server found. dri2 connection failed! 
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_CUSTOM)  No devices found in platform
X server found. dri2 connection failed! 
X server found. dri2 connection failed! 
X server found. dri2 connection failed! 
X server found. dri2 connection failed! 
X server found. dri2 connection failed! 
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_ALL)  Success (1)
    Platform Name                                 Intel Gen OCL Driver
    Device Name                                   Intel(R) HD Graphics Haswell Ultrabook GT3 reserved

ICD loader properties
  ICD loader Name                                 OpenCL ICD Loader
  ICD loader Vendor                               OCL Icd free software
  ICD loader Version                              2.2.11
  ICD loader Profile                              OpenCL 2.1
```

And the error message trying to open ClearVolume on a Z stack:

```
ClearGLWindow: GLProfile[GL4/GL4.hw]
1.0
1.0
1.0
Linuxjava.lang.NullPointerException
	at badtrack.email.GmailBadTrackNotifier.getUniqueId(GmailBadTrackNotifier.java:73)
	at badtrack.email.GmailBadTrackNotifier.notify(GmailBadTrackNotifier.java:51)
	at badtrack.BadTrack$1.uncaughtException(BadTrack.java:198)
	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1057)
	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1052)
	at java.lang.Thread.dispatchUncaughtException(Thread.java:1952)
java.lang.NullPointerException
	at cleargl.GLTexture.<init>(GLTexture.java:141)
	at clearvolume.renderer.cleargl.ClearGLVolumeRenderer.ensureTextureAllocated(ClearGLVolumeRenderer.java:630)
	at clearvolume.renderer.cleargl.ClearGLVolumeRenderer.displayInternal(ClearGLVolumeRenderer.java:508)
	at clearvolume.renderer.cleargl.ClearGLVolumeRenderer.display(ClearGLVolumeRenderer.java:490)
	at jogamp.opengl.GLDrawableHelper.displayImpl(GLDrawableHelper.java:692)
	at jogamp.opengl.GLDrawableHelper.display(GLDrawableHelper.java:674)
	at jogamp.opengl.GLAutoDrawableBase$2.run(GLAutoDrawableBase.java:443)
	at jogamp.opengl.GLDrawableHelper.invokeGLImpl(GLDrawableHelper.java:1293)
	at jogamp.opengl.GLDrawableHelper.invokeGL(GLDrawableHelper.java:1147)
	at com.jogamp.newt.opengl.GLWindow.display(GLWindow.java:759)
	at jogamp.opengl.GLAutoDrawableBase.defaultWindowResizedOp(GLAutoDrawableBase.java:260)
	at com.jogamp.newt.opengl.GLWindow.access$200(GLWindow.java:119)
	at com.jogamp.newt.opengl.GLWindow$2.windowResized(GLWindow.java:141)
	at jogamp.newt.WindowImpl.consumeWindowEvent(WindowImpl.java:4383)
	at jogamp.newt.WindowImpl.sendWindowEvent(WindowImpl.java:4317)
	at jogamp.newt.WindowImpl.sizeChanged(WindowImpl.java:4520)
	at jogamp.newt.WindowImpl.sizePosMaxInsetsVisibleChanged(WindowImpl.java:4864)
	at jogamp.newt.driver.x11.DisplayDriver.DispatchMessages0(Native Method)
	at jogamp.newt.driver.x11.DisplayDriver.dispatchMessagesNative(DisplayDriver.java:112)
	at jogamp.newt.DisplayImpl.dispatchMessages(DisplayImpl.java:753)
	at jogamp.newt.DisplayImpl$7.run(DisplayImpl.java:672)
	at jogamp.newt.DefaultEDTUtil$NEDT.run(DefaultEDTUtil.java:347)
java.lang.NullPointerException
	at clearvolume.renderer.cleargl.ClearGLVolumeRenderer.displayInternal(ClearGLVolumeRenderer.java:571)
	at clearvolume.renderer.cleargl.ClearGLVolumeRenderer.display(ClearGLVolumeRenderer.java:490)
	at jogamp.opengl.GLDrawableHelper.displayImpl(GLDrawableHelper.java:692)
	at jogamp.opengl.GLDrawableHelper.display(GLDrawableHelper.java:674)
	at jogamp.opengl.GLAutoDrawableBase$2.run(GLAutoDrawableBase.java:443)
	at jogamp.opengl.GLDrawableHelper.invokeGLImpl(GLDrawableHelper.java:1293)
	at jogamp.opengl.GLDrawableHelper.invokeGL(GLDrawableHelper.java:1147)
	at com.jogamp.newt.opengl.GLWindow.display(GLWindow.java:759)
	at jogamp.opengl.GLAutoDrawableBase.defaultWindowRepaintOp(GLAutoDrawableBase.java:215)
	at com.jogamp.newt.opengl.GLWindow.access$100(GLWindow.java:119)
	at com.jogamp.newt.opengl.GLWindow$2.windowRepaint(GLWindow.java:136)
	at jogamp.newt.WindowImpl.consumeWindowEvent(WindowImpl.java:4401)
	at jogamp.newt.WindowImpl.consumeEvent(WindowImpl.java:3372)
	at jogamp.newt.WindowImpl.doEvent(WindowImpl.java:3318)
	at jogamp.newt.WindowImpl.windowRepaint(WindowImpl.java:4715)
	at jogamp.newt.driver.x11.DisplayDriver.DispatchMessages0(Native Method)
	at jogamp.newt.driver.x11.DisplayDriver.dispatchMessagesNative(DisplayDriver.java:112)
	at jogamp.newt.DisplayImpl.dispatchMessages(DisplayImpl.java:753)
	at jogamp.newt.DisplayImpl$7.run(DisplayImpl.java:672)
	at jogamp.newt.DefaultEDTUtil$NEDT.run(DefaultEDTUtil.java:347)
java.lang.NullPointerException
	at clearvolume.renderer.cleargl.ClearGLVolumeRenderer.displayInternal(ClearGLVolumeRenderer.java:571)
	at clearvolume.renderer.cleargl.ClearGLVolumeRenderer.display(ClearGLVolumeRenderer.java:490)
	at jogamp.opengl.GLDrawableHelper.displayImpl(GLDrawableHelper.java:692)
	at jogamp.opengl.GLDrawableHelper.display(GLDrawableHelper.java:674)
	at jogamp.opengl.GLAutoDrawableBase$2.run(GLAutoDrawableBase.java:443)
	at jogamp.opengl.GLDrawableHelper.invokeGLImpl(GLDrawableHelper.java:1293)
	at jogamp.opengl.GLDrawableHelper.invokeGL(GLDrawableHelper.java:1147)
	at com.jogamp.newt.opengl.GLWindow.display(GLWindow.java:759)
	at jogamp.opengl.GLAutoDrawableBase.defaultWindowRepaintOp(GLAutoDrawableBase.java:215)
	at com.jogamp.newt.opengl.GLWindow.access$100(GLWindow.java:119)
	at com.jogamp.newt.opengl.GLWindow$2.windowRepaint(GLWindow.java:136)
	at jogamp.newt.WindowImpl.consumeWindowEvent(WindowImpl.java:4401)
	at jogamp.newt.WindowImpl.consumeEvent(WindowImpl.java:3372)
	at jogamp.newt.WindowImpl.doEvent(WindowImpl.java:3318)
	at jogamp.newt.WindowImpl.windowRepaint(WindowImpl.java:4715)
	at jogamp.newt.WindowImpl.windowRepaint(WindowImpl.java:4694)
	at com.jogamp.newt.opengl.GLWindow.windowRepaint(GLWindow.java:810)
	at com.jogamp.newt.awt.NewtCanvasAWT.paint(NewtCanvasAWT.java:732)
	at sun.awt.RepaintArea.paintComponent(RepaintArea.java:264)
	at sun.awt.X11.XRepaintArea.paintComponent(XRepaintArea.java:64)
	at sun.awt.RepaintArea.paint(RepaintArea.java:240)
	at sun.awt.X11.XComponentPeer.handleEvent(XComponentPeer.java:584)
	at java.awt.Component.dispatchEventImpl(Component.java:4967)
	at java.awt.Component.dispatchEvent(Component.java:4713)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
javax.mail.AuthenticationFailedException: 534-5.7.14 <https://accounts.google.com/signin/continue?sarp=1&scc=1&plt=AKgnsbvs
534-5.7.14 jQsLXOP5FOWNL4F-8TgTN9-nT-uc_RZM2d5FvLV5x34RQ6-lYSMiSahqGeYY1-ue2M5Skj
534-5.7.14 hC7K22Yn0FxNKx5pdvgO8q4BEGt6KNFNfh6v7HHfiHxKcknZuzxacTnhxEJ07KN8rOHmdr
534-5.7.14 WgGt9nhqc-eZq-1pqRCLvi8DlFCh31WyTMbeZG8eJifciBwvR_2GlQTu_-CYhB74RTQseG
534-5.7.14 HbZqe9-hGPKLQMUkflsXfaX0O76V8> Please log in via your web browser and
534-5.7.14 then try again.
534-5.7.14  Learn more at
534 5.7.14  https://support.google.com/mail/answer/78754 k43sm8577251qtc.75 - gsmtp

	at com.sun.mail.smtp.SMTPTransport$Authenticator.authenticate(SMTPTransport.java:826)
	at com.sun.mail.smtp.SMTPTransport.authenticate(SMTPTransport.java:761)
	at com.sun.mail.smtp.SMTPTransport.protocolConnect(SMTPTransport.java:685)
	at javax.mail.Service.connect(Service.java:317)
	at javax.mail.Service.connect(Service.java:176)
	at javax.mail.Service.connect(Service.java:125)
	at javax.mail.Transport.send0(Transport.java:253)
	at javax.mail.Transport.send(Transport.java:124)
	at badtrack.email.GmailClient.sendMessage(GmailClient.java:83)
	at badtrack.email.GmailBadTrackNotifier.notify(GmailBadTrackNotifier.java:65)
	at badtrack.BadTrack$1.uncaughtException(BadTrack.java:198)
	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1057)
	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1052)
	at java.lang.Thread.dispatchUncaughtException(Thread.java:1952)
com.jogamp.opengl.util.AnimatorBase$UncaughtAnimatorException: com.jogamp.opengl.GLException: Caught UnsatisfiedLinkError: Could not initialize native OpenCL library. Implementation library could not be loaded on thread SciJava-3a23140e-Thread-0-FPSAWTAnimator#00-Timer0
	at com.jogamp.opengl.util.AWTAnimatorImpl.display(AWTAnimatorImpl.java:92)
	at com.jogamp.opengl.util.AnimatorBase.display(AnimatorBase.java:452)
	at com.jogamp.opengl.util.FPSAnimator$MainTask.run(FPSAnimator.java:178)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)
Caused by: com.jogamp.opengl.GLException: Caught UnsatisfiedLinkError: Could not initialize native OpenCL library. Implementation library could not be loaded on thread SciJava-3a23140e-Thread-0-FPSAWTAnimator#00-Timer0
	at com.jogamp.opengl.GLException.newGLException(GLException.java:76)
	at jogamp.opengl.GLDrawableHelper.invokeGLImpl(GLDrawableHelper.java:1327)
	at jogamp.opengl.GLDrawableHelper.invokeGL(GLDrawableHelper.java:1147)
	at com.jogamp.newt.opengl.GLWindow.display(GLWindow.java:759)
	at com.jogamp.opengl.util.AWTAnimatorImpl.display(AWTAnimatorImpl.java:81)
	... 4 more
Caused by: java.lang.UnsatisfiedLinkError: Could not initialize native OpenCL library. Implementation library could not be loaded
	at org.jocl.LibInitializer.initNativeLibrary(LibInitializer.java:74)
	at org.jocl.CL.loadNativeLibrary(CL.java:66)
	at org.jocl.CL.<clinit>(CL.java:51)
	at clearcl.backend.jocl.ClearCLBackendJOCL.<clinit>(ClearCLBackendJOCL.java:61)
	at clearcl.backend.ClearCLBackends.getBackendList(ClearCLBackends.java:30)
	at clearcl.backend.ClearCLBackends.getFunctionalBackend(ClearCLBackends.java:65)
	at clearcl.backend.ClearCLBackends.getBestBackend(ClearCLBackends.java:91)
	at clearvolume.renderer.opencl.OpenCLDevice.initCL(OpenCLDevice.java:48)
	at clearvolume.renderer.opencl.OpenCLVolumeRenderer.initVolumeRenderer(OpenCLVolumeRenderer.java:130)
	at clearvolume.renderer.cleargl.ClearGLVolumeRenderer.init(ClearGLVolumeRenderer.java:818)
	at jogamp.opengl.GLDrawableHelper.init(GLDrawableHelper.java:644)
	at jogamp.opengl.GLDrawableHelper.init(GLDrawableHelper.java:667)
	at jogamp.opengl.GLAutoDrawableBase$1.run(GLAutoDrawableBase.java:431)
	at jogamp.opengl.GLDrawableHelper.invokeGLImpl(GLDrawableHelper.java:1291)
	... 7 more
```

By the way what the status of the project? How does it compare to the *still in development* [SciView](https://github.com/scenerygraphics/SciView).

Thank you.

**Comment by fjug** [comment]
@royerloic Is this the bug tracker???

**Comment by royerloic** [comment]
The bug tracker is not present fro some time already,
must be an old version of CV in the wilde…

**Comment by HaaPut** [comment]
So..... is there no way to report an issue? 
If I have an old-wild version how can I get the latest-tame one? (I installed following instruction [here](https://imagej.net/ClearVolume) ).

**Comment by fjug** [comment]
Our discussion referred to an old bug submission module we once have used.
When did you install ClearVolume? If either the entire Fiji or only ClearVolume is ‘ancient’ you might try to download the latest Fiji and install ClearVolume as described on the page you pointed at.
What happened?!?

**Comment by HaaPut** [comment]
My Fiji install is a few months old and ClearVolume is 1 day old.. I don't think that counts as ancient :P.. 
The install works fine but when I try to load a ( 3D ome-tiff image) volume it spits out the above error on the console. The GUI is displayed but the region for displaying volume is a dark void!
............................................................................................................
ClearVolume Version : 1.3.20
Fiji Properties...
java.version: 1.8.0_66
  java.vendor: Oracle Corporation
  os.name: Linux
  os.version: 4.4.0-124-generic
  os.arch: amd64
  file.separator: /
  path.separator: :
  line.separator: <lf>
 user.name: .
  user.home: HOME
  user.dir: HOME
  user.country: 
  file.encoding: UTF-8
  java.home: HOME/opt/Fiji.app/java/linux-amd64/jdk1.8.0_66/jre
  java.class.path: HOME/opt/Fiji.app/jars/imagej-launcher-4.0.5.jar
  java.ext.dirs: HOME/opt/Fiji.app/java/linux-amd64/jdk1.8.0_66/jre/lib/ext:/usr/java/packages/lib/ext
  java.io.tmpdir: /tmp

  IJ.getVersion: 2.0.0-rc-67/1.52c
  IJ.getFullVersion: 1.52c99
  IJ.javaVersion: 8
  IJ.isLinux: true
  IJ.isMacintosh: false
  IJ.isMacOSX: false
  IJ.isWindows: false
  IJ.is64Bit: true

All Java Properties
  ij.dir: HOME/opt/Fiji.app
  java.runtime.name: Java(TM) SE Runtime Environment
  fiji.dir: HOME/opt/Fiji.app
  imagej.dir: HOME/opt/Fiji.app
  sun.boot.library.path: HOME/opt/Fiji.app/java/linux-amd64/jdk1.8.0_66/jre/lib/amd64
  java.vm.version: 25.66-b17
  fiji.defaultLibPath: lib/amd64/server/libjvm.so
  java.vm.vendor: Oracle Corporation
  java.vendor.url: http://java.oracle.com/
  path.separator: :
  java.vm.name: Java HotSpot(TM) 64-Bit Server VM
  file.encoding.pkg: sun.io
  user.country:
  sun.os.patch.level: unknown
  java.vm.specification.name: Java Virtual Machine Specification
  user.dir: HOME
  java.runtime.version: 1.8.0_66-b17
  java.awt.graphicsenv: sun.awt.X11GraphicsEnvironment
  java.endorsed.dirs: HOME/opt/Fiji.app/java/linux-amd64/jdk1.8.0_66/jre/lib/endorsed
  os.arch: amd64
  java.io.tmpdir: /tmp
  line.separator: 

  java.vm.specification.vendor: Oracle Corporation
  os.name: Linux
  sun.jnu.encoding: UTF-8
  java.library.path: HOME/torch/install/lib:/usr/local/cuda/lib64::HOME/opt/Fiji.app/lib/linux64:HOME/opt/Fiji.app/mm/linux64
  sun.awt.enableExtraMouseButtons: true
  java.specification.name: Java Platform API Specification
  java.class.version: 52.0
  sun.management.compiler: HotSpot 64-Bit Tiered Compilers
  os.version: 4.4.0-124-generic
  user.home: HOME
  user.timezone: 
  java.awt.printerjob: sun.print.PSPrinterJob
  file.encoding: UTF-8
  java.specification.version: 1.8
  plugins.dir: HOME/opt/Fiji.app
  java.class.path: HOME/opt/Fiji.app/jars/imagej-launcher-4.0.5.jar
  user.name: 
  java.vm.specification.version: 1.8
  java.home:HOME/opt/Fiji.app/java/linux-amd64/jdk1.8.0_66/jre
  sun.arch.data.model: 64
  user.language: en
  java.specification.vendor: Oracle Corporation
  awt.toolkit: sun.awt.X11.XToolkit
  java.vm.info: mixed mode
  java.version: 1.8.0_66
  java.ext.dirs: HOME/opt/Fiji.app/java/linux-amd64/jdk1.8.0_66/jre/lib/ext:/usr/java/packages/lib/ext
  sun.boot.class.path: HOME/opt/Fiji.app/java/linux-amd64/jdk1.8.0_66/jre/lib/resources.jar:HOME/opt/Fiji.app/java/linux-amd64/jdk1.8.0_66/jre/lib/rt.jar:HOME/opt/Fiji.app/java/linux-amd64/jdk1.8.0_66/jre/lib/sunrsasign.jar:HOME/opt/Fiji.app/java/linux-amd64/jdk1.8.0_66/jre/lib/jsse.jar:HOME/opt/Fiji.app/java/linux-amd64/jdk1.8.0_66/jre/lib/jce.jar:HOME/opt/Fiji.app/java/linux-amd64/jdk1.8.0_66/jre/lib/charsets.jar:HOME/opt/Fiji.app/java/linux-amd64/jdk1.8.0_66/jre/lib/jfr.jar:HOME/opt/Fiji.app/java/linux-amd64/jdk1.8.0_66/jre/classes
  java.vendor: Oracle Corporation
  ij.executable: HOME/opt/Fiji.app/ImageJ-linux64
  python.cachedir.skip: true
  file.separator: /
  java.vendor.url.bug: http://bugreport.sun.com/bugreport/
  sun.font.fontmanager: sun.awt.X11FontManager
  sun.io.unicode.encoding: UnicodeLittle
  sun.cpu.endian: little
  sun.desktop: gnome
  fiji.executable: HOME/opt/Fiji.app/ImageJ-linux64
  sun.cpu.isalist: 

....................................................................................
 If you need more details please let me know.

**Comment by skalarproduktraum** [comment]
@fjug @royerloic,

could it be that the latest change to the update site ate some dependencies? @HaaPut's error is looking as if a dependency JAR for JOCL is missing. Plus, there's also BadTrack there, which should have been gone since quite a bit.

**Comment by fjug** [comment]
@skalarproduktraum On the update site I've only placed the new (and fixed) clearvolume-imglib2 bridge. Maybe while uploading I removed some dependencies within the updater, but why do you think it might cause this problem? 
@HaaPut I would love if you could download a fresh Fiji and then activate the ClearVolume update site. It would save us a lot of digging time if it would turn out that it simply worked then. (Ideally you'd not even turn on any other update site before testing, only ClearVolume...)

Thanks to both of you,
Florian

**Comment by skalarproduktraum** [comment]
@fjug Because the bottom-most error in the stack trace is a UnsatisfiedLinkError bringing me to ...
@HaaPut, I've just seen a piece that I had missed in the stack trace before, namely `
```
java.lang.UnsatisfiedLinkError: /tmp/libJOCL_2_0_0-linux-x86_64.so: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /tmp/libJOCL_2_0_0-linux-x86_64.so)
```

Apparently, the JOCL .so it's shipping is slightly old, that ABI version is from GCC 4.9... I guess there's two options here:
* @HaaPut installs GCC 4.9 and sees if that fixes the issue
* we bump JOCL to 2.0.1, which should bring newer binaries. Maybe we can try this by adding it as a dependency directly to imglib2-clearvolume, instead of going through the ClearCL-ClearVolume-imglib2-clearvolume chain. What do you think, @fjug?

**Comment by HaaPut** [comment]
@skalarproduktraum updating GCC is not a feasible option for me. I can try a fresh install of fiji if you think that may help @fjug . 
Note: I have been regularly updating my fiji install.. my current version is:
IJ.getVersion: 2.0.0-rc-67/1.52c
IJ.getFullVersion: 1.52c99
ClearVolume Version : 1.3.20
